<a href="https://colab.research.google.com/github/Jonas-Godoi/AtivadesIntrodua-oBigData/blob/main/Python_aulas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# encoding:utf-8

def ler_fasta(arquivo):
    sequencia = ''
    lista = []
    with open(arquivo, 'r') as fasta:
            sequencia = ''
            for linha in fasta:
                if not linha.startswith('>'):
                    sequencia += linha
            lista.append(sequencia)

    return lista

# testando...
lista = ler_fasta("sequence.fasta")

def contarA(dna):
  return dna[0].count('A')
def contarG(dna):
  return dna[0].count('G')
def contarC(dna):
  return dna[0].count('C')
def contarT(dna):
  return dna[0].count('T')

QuantidadeA = contarA(lista)
QuantidadeG = contarG(lista)
QuantidadeC = contarC(lista)
QuantidadeT = contarT(lista)

print("Quantidade de dna A:", QuantidadeA)
print("Quantidade de dna G:", QuantidadeG)
print("Quantidade de dna C:", QuantidadeC)
print("Quantidade de dna T:", QuantidadeT)

print('')
quantidade_total = len(lista[0])

percentual_a = (QuantidadeA / quantidade_total) * 100
percentual_t = (QuantidadeT / quantidade_total) * 100
percentual_g = (QuantidadeG / quantidade_total) * 100
percentual_c = (QuantidadeC / quantidade_total) * 100

# Exibir os percentuais
print(f"Percentual de DNA A: {percentual_a:.2f}%")
print(f"Percentual de DNA T: {percentual_t:.2f}%")
print(f"Percentual de DNA G: {percentual_g:.2f}%")
print(f"Percentual de DNA C: {percentual_c:.2f}%")

Quantidade de dna A: 9709674
Quantidade de dna G: 5421151
Quantidade de dna C: 5435374
Quantidade de dna T: 9697113

Percentual de DNA A: 31.46%
Percentual de DNA T: 31.42%
Percentual de DNA G: 17.57%
Percentual de DNA C: 17.61%


In [ ]:
import pandas as pd
import numpy as np
#idades =[np.random.randint(0, 100)for _ in range(1000)]
idades =[np.random.randint(0, 100)for _ in range(1000)]
lista = pd.Series(idades)

menoresde21 = lista[lista <= 21]
maiores21 = lista[lista > 21]
trocaIdade = lista.copy()
mediaMaior = maiores21.mean()

for i in range(1000):
    if trocaIdade[i] < 21:
        trocaIdade[i] = mediaMaior


lista2 = pd.Series(trocaIdade)

media = lista.mean()
mediana = lista.median()
moda = lista.mode()

print("Média:", media)
print("Mediana:", mediana)
print("Moda:", moda)



print("")
print("lista de idades:")
print(lista)
print("")
print("")
print("Media das idades maiores:")
print(mediaMaior)
print("")
print("")
print("Troca de idades")
print(lista2)

Média: 49.92
Mediana: 50.0
Moda: 0    67
dtype: int64

lista de idades:
0      98
1      15
2      96
3      41
4      39
       ..
995    29
996     1
997    22
998    33
999    71
Length: 1000, dtype: int64


Media das idades maiores:
60.30555555555556


Troca de idades
0      98.000000
1      60.305556
2      96.000000
3      41.000000
4      39.000000
         ...    
995    29.000000
996    60.305556
997    22.000000
998    33.000000
999    71.000000
Length: 1000, dtype: float64


<ipython-input-60-9930fdbfef5c>:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '60.30555555555556' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  trocaIdade[i] = mediaMaior


# Aula dia  14/08/2024


In [ ]:
#Mostrar linhas verdadeiras e falsas
import pandas as pd
import numpy as np

str = pd.Series(["Mauricio","Fatec",np.nan,"Professor"])
str
str[0] = None
str
str.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
#Limpar linhas que estão nulas
from numpy import nan as NA
datas = pd.Series([1,2,3,NA,5])
datas.dropna()

0    1.0
1    2.0
2    3.0
4    5.0
dtype: float64

In [ ]:
#Limpar linhas que estão nulas
from numpy import nan as NA
dados = pd.DataFrame([['Ana', 6.5, 3.], ['Luiz', NA, NA], [NA, NA, NA], ['Maria', 6.5, NA]])
dados
dados_limpos = dados.dropna()
dados_limpos

In [ ]:
#Limpar somente linhas totalmente nulas
from numpy import nan as NA
dados = pd.DataFrame([['Ana', 6.5, 3.], ['Luiz', NA, NA], [NA, NA, NA], ['Maria', 6.5, NA]])
dados
dados_limpos = dados.dropna(how='all')
dados_limpos

In [ ]:
#Limpar somente colunas totalmente nulas
from numpy import nan as NA
dados = pd.DataFrame([['Ana', 6.5, 3.], ['Luiz', NA, NA], [NA, NA, NA], ['Maria', 6.5, NA]])
dados[4]= NA
dados_limpos = dados.dropna(axis=1,how='all')
dados_limpos

0    1    2
0    Ana  6.5  3.0
1   Luiz  NaN  NaN
2    NaN  NaN  NaN
3  Maria  6.5  NaN

In [ ]:
#Faz com que seja colocado valores nulos em colunas ultilizando o iloc
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df


In [ ]:
#Comando tresh faz com que as linhas que tenham 2 valores nulos sejam removidas
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df.dropna(thresh=2)


In [ ]:
#Comando fillna faz com que seja subistitudos os falores NA pelo vavor do parametro
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df.fillna(0)


In [ ]:
#Este comando pega a media das notas e atribue o valor aos espaços nulos
notas =pd.Series([7,2,5,4,5,NA,NA,NA,10,10])
media = notas.mean()
#este comando arredonda a media a 2 valores
media = round(media,2)
notas.fillna(media)

0     7.00
1     2.00
2     5.00
3     4.00
4     5.00
5     6.14
6     6.14
7     6.14
8    10.00
9    10.00
dtype: float64

In [ ]:
#Este comando pega a media das notas e atribue o valor aos espaços nulos
notas = pd.Series([7.6,2,5,4,5,NA,NA,NA,10,10])
notas.fillna(notas.dropna().mean())

In [ ]:
import pandas as pd
import numpy as np

numeros = pd.DataFrame(np.random.randn(1000,4))
numeros.describe()
col = numeros[2]
col[np.abs(col) > 3]


233    3.681377
425    3.028240
Name: 2, dtype: float64

In [ ]:
import pandas as pd
import numpy as np
# Encontrar as linhas onde qualquer valor é maior que 3 ou menor que -3
numeros = pd.DataFrame(np.random.randn(1000,4))
numeros_filtrados = numeros[(np.abs(numeros) > 3).any(axis=1)]
numeros_filtrados

In [ ]:
import pandas as pd
import numpy as np
# Encontrar os numeros que estão discrepantes e subistituilos por 3
numeros = pd.DataFrame(np.random.randn(1000,4))
numeros[np.abs(numeros) > 3] = np.sign(numeros) * 3
numeros.describe()


In [ ]:
#Exercicio dia 14/08/2024

import pandas as pd
df = pd.read_csv('Exasens.csv')
lista_pandas = pd.Series(df['Age'])
lista_pandas
meida = lista_pandas.mean()
trocar =lista_pandas.fillna(meida)
trocar


0      48.736842
1      48.736842
2      77.000000
3      72.000000
4      73.000000
         ...    
396    49.000000
397    37.000000
398    29.000000
399    51.000000
400    40.000000
Name: Age, Length: 401, dtype: float64

## Aula dia 21/08/2024

In [ ]:
import pandas as pd
base_credito = pd.read_csv('/content/risco_credito.csv',sep=';')
base_credito

historia  divida garantias     renda     risco
0           ruim    alta   nenhuma      0_15      alto
1   desconhecida    alta   nenhuma     15_35      alto
2   desconhecida   baixa   nenhuma     15_35  moderado
3   desconhecida   baixa   nenhuma  acima_35      alto
4   desconhecida   baixa   nenhuma  acima_35     baixo
5   desconhecida   baixa  adequada  acima_35     baixo
6           ruim   baixa   nenhuma      0_15      alto
7           ruim  baixa   adequada  acima_35  moderado
8            boa   baixa   nenhuma  acima_35  moderado
9            boa    alta  adequada  acima_35     baixo
10           boa    alta   nenhuma      0_15      alto
11           boa    alta   nenhuma     15_35  moderado
12           boa    alta   nenhuma  acima_35     baixo
13          ruim    alta   nenhuma     15_35      alto

In [ ]:
#Neste codigo ele seleciona todas as linhas e separa todos os elementos da coluna 0 até a coluna 3
x_risco_credito = base_credito.iloc[:,0:4].values
x_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa ', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [ ]:
#Neste codigo ele seleciona todas as linhas,porem ele seleciona apenas os valores da coluna 4
y_risco_credito = base_credito.iloc[:,4].values
y_risco_credito


array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'moderado', 'baixo', 'alto', 'moderado', 'baixo',
       'alto'], dtype=object)

In [ ]:
#Este codigo importa a biblioteca "LabelEncoder" e converte os valores categoricos em numericos
from sklearn.preprocessing import LabelEncoder
label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantia = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [ ]:
#Este codigo transformas os dados em numerico e devolve eles nas tabelas
x_risco_credito[:,0] = label_encoder_historia.fit_transform(x_risco_credito[:,0])
x_risco_credito[:,1] = label_encoder_divida.fit_transform(x_risco_credito[:,1])
x_risco_credito[:,2] = label_encoder_garantia.fit_transform(x_risco_credito[:,2])
x_risco_credito[:,3] = label_encoder_renda.fit_transform(x_risco_credito[:,3])
x_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 2, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [ ]:
#Este codigo cria um treinamento onde adicina os valores de treino e teste
from sklearn.model_selection import train_test_split
x_treino,x_teste,y_treino,y_teste = train_test_split(x_risco_credito,y_risco_credito,test_size=0.10,random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
naive_risco = GaussianNB()
naive_risco.fit(x_treino,y_treino)

GaussianNB()

In [ ]:
#Previsões
#historia = Boa 0,Divida = alta 0,garantia = nenhuma 1,renda >=35 2
#historia = Ruim 2,Divida = alta 0,garantia = adequada 0,renda <15 0
previsoes = naive_risco.predict([[0,0,1,2],[2,0,0,0]])
previsoes


array(['baixo', 'moderado'], dtype='<U8')

In [ ]:
previsoes = naive_risco.predict(x_teste)
previsoes

Exercicio 21/08/2024

In [ ]:
import pandas as pd
base_credito = pd.read_csv('/content/credit-data.csv')
base_credito

clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [ ]:
# prompt: Crie um codigo para encontrar os valores negativos na tabela credit-data

# Encontrar valores negativos na coluna 'age' e substituí-los pela média das idades positivas
media_idades_positivas = base_credito[base_credito['age'] > 0]['age'].mean()
base_credito.loc[base_credito['age'] < 0, 'age'] = media_idades_positivas

# Verificar se ainda existem valores negativos na coluna 'age'
print(base_credito[base_credito['age'] < 0])


Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []


In [ ]:
# prompt: Crie uma variavel "previsores" que armazena os valores (clientid,income,age e loan) e uma variavel classe que vai adicionar o valor (default)

previsores = base_credito.iloc[:, 1:4].values
classe = base_credito.iloc[:, 4].values


In [ ]:
#Neste codigo é feito a transformação dos valores nulos em previsões
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer = imputer.fit(previsores)
previsores = imputer.transform(previsores)
previsores


array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)
previsores

array([[ 1.45393393,  1.36538005,  1.20281942],
       [-0.76217555,  0.54265932,  0.69642695],
       [ 0.83682073,  1.67417101,  1.17471147],
       ...,
       [-0.07122592, -0.97448606,  0.35420081],
       [-0.11000289,  1.73936652, -0.92675625],
       [ 1.682986  ,  1.14917551,  0.96381038]])

In [ ]:
from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25, random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)

GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
previsoes = classificador.predict(previsores_teste)
previsoes

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Matriz de confusão
matriz_confusao = confusion_matrix(classe_teste, previsoes)
print("Matriz de Confusão:")
print(matriz_confusao)

# Acurácia
acuracia = accuracy_score(classe_teste, previsoes)
print("Acurácia:")
print(acuracia)

Matriz de Confusão:
[[428   8]
 [ 23  41]]
Acurácia:
0.938
